config/routes.rb
Rails.application.routes.draw do
   root to: "lists#index"
  resources :lists do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :overview, :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to @list, notice: "Bookmark was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bookmark = Bookmark.find(params[id])
  end

  def destroy
    @bookmark.destroy!
    redirect_to bookmark_url, notice: "Bookmark was successfully destroy"
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: %i[show edit update destroy]
  def index
  @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully create"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: "List was successfully update"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy!
    redirect_to list_url, notice: "List was successfully destroy"
  end

  private

  def set_list
    @list = @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :movie, :bookmark)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>


  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>


  <p>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<h1>My list</h1>

<div id="list">
  <% @lists.each do |list| %>
    <%= render list %>
    <p>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>


<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<%= render @list %>


<p><strong>Movies</strong></p>
<ul class="list-group">
  <% @list.movies.each do |movie| %>
    <li class="list-group-item">
      <%= movie.title %>
      <%= movie.overview %>
      <%= image_tag movie.poster_url %>

    </li>
  <% end %>

<%= link_to "Add a movie", new_list_bookmark_path(@list) %>
<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>